### ISSUE TITLE
Competitive Companion's CodeforcesProblemParser Not Working

### ISSUE THREAD

**Issue by mrpawan-gupta** [jmerle/competitive-companion#250]
Generating  This error on Chrome Browser 
```
VM79 content.js:1 TypeError: Cannot read properties of undefined (reading 'textContent')
    at CodeforcesProblemParser.parseMainProblem (common.js:1:306036)
    at CodeforcesProblemParser.parse (common.js:1:305320)
    at l (content.js:1:320)
    at content.js:1:1220
l @ VM79 content.js:1
```

**Comment by jmerle** [comment]
I cannot reproduce this error on the problems of some recent contests ([1](https://codeforces.com/contest/1687) [2](https://codeforces.com/contest/1690) [3](https://codeforces.com/contest/1689) [4](https://codeforces.com/contest/1697) [5](https://codeforces.com/contest/1692)). Can you please share a link to a problem it is failing on?

**Comment by DevanshMudgal** [comment]
I am also facing a problem in running the extension on chrome and firefox. 
`content.js:1 TypeError: Cannot read properties of null (reading 'textContent')
    at CodeforcesProblemParser.parseMainProblem (common.js:1:305257)
    at CodeforcesProblemParser.parse (common.js:1:305092)
    at l (content.js:1:320)
    at e (content.js:1:1567)
    at common.js:1:248433
l @ content.js:1
`
Please let me know how to resolve this issue

**Comment by DevanshMudgal** [comment]
There seems to be another error in the extension in VSC it shows, 

> CPH server encountered an error: "listen EADDRINUSE: address already in use :::27121" , companion may not work.

**Comment by jmerle** [comment]
> I am also facing a problem in running the extension on chrome and firefox. `content.js:1 TypeError: Cannot read properties of null (reading 'textContent') at CodeforcesProblemParser.parseMainProblem (common.js:1:305257) at CodeforcesProblemParser.parse (common.js:1:305092) at l (content.js:1:320) at e (content.js:1:1567) at common.js:1:248433 l @ content.js:1 ` Please let me know how to resolve this issue

Please share a link to the problem where you see this error when you parse it.

> There seems to be another error in the extension in VSC it shows,
> 
> > CPH server encountered an error: "listen EADDRINUSE: address already in use :::27121" , companion may not work.

Competitive Companion only parses problems and sends the extracted data to external tools. These external tools are not made by me, you should send this issue to the developer(s) of the tool that you are using.

**Comment by mrpawan-gupta** [comment]
@jmerle The CPH problem parser Sometimes gives out this error. Now it's working fine! I think The error is due to dependencies of Coding Platforms Kindly go through it. and Check the issue.

**Comment by jmerle** [comment]
> I think The error is due to dependencies of Coding Platforms Kindly go through it. and Check the issue.

I have no idea what you mean here, but good to hear that the error is gone. Next time please provide the link to the problem it's failing on, if I cannot reproduce the error on my machine I usually cannot fix it for you.

I'm leaving this issue open for now to see if @DevanshMudgal can still reproduce his error and is able to provide a link to the problem it's failing on.

**Comment by mrpawan-gupta** [comment]
@jmerle The parser is not working for HackerEarth. I am using Chrome 
this is the link:- https://www.hackerearth.com/practice/codemonk/
problem (Monk and Rotation)
also, the error is the same

**Comment by jmerle** [comment]
> @jmerle The parser is not working for HackerEarth. I am using Chrome this is the link:- [hackerearth.com/practice/codemonk](https://www.hackerearth.com/practice/codemonk/) problem (Monk and Rotation) also, the error is the same

Thanks, that's something I can fix. Fixed in f47331cf2c783a58d8d7adc80c8b0b305487bcd5, will be released later today.

**Comment by Sanu3007** [comment]
@jmerle The parser is not working for me for the problems of codechef.
Below is the question link:
https://www.codechef.com/submit/PROGLANG

The error producing is:

content.js:1 TypeError: Cannot read properties of null (reading 'textContent')
    at CodeChefNewProblemParser.parse (common.js:1:297950)
    at l (content.js:1:320)
    at content.js:1:1220
l @ content.js:1
await in l (async)
(anonymous) @ content.js:1
Promise.then (async)
e @ content.js:1
(anonymous) @ common.js:1

**Comment by jmerle** [comment]
> @jmerle The parser is not working for me for the problems of codechef. Below is the question link: [codechef.com/submit/PROGLANG](https://www.codechef.com/submit/PROGLANG)
> 
> The error producing is:
> 
> content.js:1 TypeError: Cannot read properties of null (reading 'textContent') at CodeChefNewProblemParser.parse (common.js:1:297950) at l (content.js:1:320) at content.js:1:1220 l @ content.js:1 await in l (async) (anonymous) @ content.js:1 Promise.then (async) e @ content.js:1 (anonymous) @ common.js:1

Fixed in 3829147a6c33ff2b1f8a874bce111598172dcc4b, will be released within 24 hours. Thanks for reporting the issue!

> > I think The error is due to dependencies of Coding Platforms Kindly go through it. and Check the issue.
> 
> I have no idea what you mean here, but good to hear that the error is gone. Next time please provide the link to the problem it's failing on, if I cannot reproduce the error on my machine I usually cannot fix it for you.
> 
> I'm leaving this issue open for now to see if @DevanshMudgal can still reproduce his error and is able to provide a link to the problem it's failing on.

I'm closing this issue now, feel free to create a new issue with the requested information if you're still seeing errors.
