### ISSUE TITLE
Extension not working on codechef

### ISSUE THREAD

**Issue by twi05** [jmerle/competitive-companion#327]
On 24th Jan 2023, when I tried to use the extension. It was not showing anything. And in the console log it throws an error:

content.js:1 TypeError: Cannot read properties of null (reading 'textContent')
    at CodeChefNewProblemParser.parse (common.js:1:341279)
    at async l (content.js:1:312)

Link of CC problem: https://www.codechef.com/problems/NTRIPLETS?tab=statement

**Comment by jmerle** [comment]
I can't reproduce this issue, are you still experiencing issues with the CodeChef parser?:
![](https://user-images.githubusercontent.com/14951909/220806586-d4e2fc4e-2ce7-4419-8a89-0d794a582b0c.png)

**Comment by jmerle** [comment]
I'm closing this issue because of inactivity. Feel free to open a new issue if you still experience problems.
