### ISSUE TITLE
Something went wrong while running Competitive Companion's BaekjoonOnlineJudgeProblemParser.

### ISSUE THREAD

**Issue by falsetru** [jmerle/competitive-companion#340]
- Problem page: https://www.acmicpc.net/problem/23261
- Error:
```javascript
content.js:1 TypeError: Cannot read properties of null (reading '1')
    at BaekjoonOnlineJudgeProblemParser.parse (common.js:1:331477)
    at l (content.js:1:320)
    at content.js:1:1263
```

**Comment by jmerle** [comment]
Fixed in 8ec7495ac06965d3aa2e41046def40e81ad2471c, will be released within a few hours. Thanks for reporting the issue!
