### ISSUE TITLE
Support acmicpc.net

### ISSUE THREAD

**Issue by EgorKulikov** [jmerle/competitive-companion#406]
Here's an example problem https://www.acmicpc.net/problem/31223

**Comment by jmerle** [comment]
Baekjoon Online Judge (aka acmicpc.net) is already supported:
![](https://github.com/jmerle/competitive-companion/assets/14951909/48a83dc1-5e93-47c2-bc33-b364ade8f3d4)

**Comment by EgorKulikov** [comment]
Thanks. I wonder why it did not work for me yesterday, but it works now

**Comment by EgorKulikov** [comment]
So, for me

- task parser works, but I have to specify judge each time
- contest parser does not work after specifying judge:
` Failed to parse task 11: TypeError: Cannot read properties of null (reading 'textContent')
    at BaekjoonOnlineJudgeProblemParser.parse (chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl/js/content.js:13:11667)
    at BaekjoonOnlineJudgeContestParser.parseTask (chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl/js/content.js:13:9243)
    at async Promise.all (index 10)
    at async BaekjoonOnlineJudgeContestParser.parse (chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl/js/content.js:13:7842)
    at async parse (chrome-extension://cjnmckjndlpiamhfimnnjmnckgghkjbl/js/content.js:49:6123)`
